export const VISIT_HOME_PAGE = 'VISIT_HOME_PAGE';
// profile
export const VISIT_PROFILE_PAGE = 'VISIT_PROFILE_PAGE';
export const VISIT_PROFILE_EDIT = 'VISIT_PROFILE_EDIT';
// games
export const VISIT_GAMES_LIST_PAGE = 'VISIT_GAMES_LIST_PAGE';
// venues
export const VISIT_VENUE = 'VISIT_VENUE';
export const VISIT_VENUE_DETAILS = 'VISIT_VENUE_DETAILS';
export const VISIT_VENUES_LIST_PAGE = 'VISIT_VENUES_LIST_PAGE';

